export * from './auth.service';
import { AuthService } from './auth.service';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './incredient.service';
import { IncredientService } from './incredient.service';
export * from './magazines.service';
import { MagazinesService } from './magazines.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './recipe.service';
import { RecipeService } from './recipe.service';
export * from './shoppingList.service';
import { ShoppingListService } from './shoppingList.service';
export * from './todo.service';
import { TodoService } from './todo.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './wiki.service';
import { WikiService } from './wiki.service';
export const APIS = [AuthService, ContractService, IncredientService, MagazinesService, ProductService, RecipeService, ShoppingListService, TodoService, UserService, WikiService];
